# Generated by Django 4.0.4 on 2022-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_equations_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='equations',
            name='exercise',
        ),
        migrations.AddField(
            model_name='answers',
            name='isCorrectAnswer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='answers',
            field=models.ManyToManyField(to='exercises.answers'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equations',
            field=models.ManyToManyField(to='exercises.equations'),
        ),
    ]
