# Generated by Django 4.0.4 on 2022-05-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_answers_exercise_remove_equations_exercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='isCorrectAnswer',
            new_name='is_correct_answer',
        ),
    ]
